set-option -g default-shell /opt/homebrew/bin/fish

set-option -g default-terminal screen-256color
set -g terminal-override 'xterm:colors=256'

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# mouse enable
set-option -g mouse on
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e'"
