[[plugins]]
repo = 'scrooloose/nerdtree'


[[plugins]]
repo = 'thinca/vim-quickrun'


[[plugins]]
repo = 'tomasr/molokai'


[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'


[[plugins]]
repo = 'bronson/vim-trailing-whitespace'


[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
